import {
  User,
  Order,
  Idea,
  EscrowTransaction,
  SponsorshipAgreement,
  ModeratedMessage,
  CreatorTierInfo,
  InnovationStory,
  InnovationPod,
} from '../types';

export const CREATOR_TIERS: CreatorTierInfo[] = [
  {
    level: 'Apprentice',
    title: 'Apprentice Maker',
    badge: '🌱',
    minCompleted: 0,
    minRating: 0.0,
    unlockedFeatures: [
      'Simple pre-scoped STEM science kits',
      'Mentor-guided build queues',
      'Class 1 safe tools (scissors, glue, breadboard, 5V Arduino)',
    ],
    maxOrderValue: 5000,
  },
  {
    level: 'Builder',
    title: 'Certified Student Builder',
    badge: '⚡',
    minCompleted: 3,
    minRating: 4.5,
    unlockedFeatures: [
      'Custom school science fair & robotics project builds',
      'BOM optimization & schematic design proposals',
      'Class 2 tools (low-voltage soldering, 3D printers with guardian consent)',
    ],
    maxOrderValue: 15000,
  },
  {
    level: 'Idea Groomer',
    title: 'Community Idea Groomer',
    badge: '💡',
    minCompleted: 8,
    minRating: 4.8,
    unlockedFeatures: [
      'Lead RFC grooming discussions with young inventors',
      'Mentor Apprentice creators across India',
      'Earn contributor ledger equity splits on groomed ideas',
    ],
    maxOrderValue: 35000,
  },
  {
    level: 'Studio Lead',
    title: 'Maker Studio Lead',
    badge: '🛠️',
    minCompleted: 15,
    minRating: 4.9,
    unlockedFeatures: [
      'Form student squads for complex engineering & research orders',
      'Direct college lab & researcher project assignments',
      'Revenue share on squad build outputs & prototyping grants',
    ],
    maxOrderValue: 100000,
  },
  {
    level: 'Young Entrepreneur',
    title: 'Young Entrepreneur Inventor',
    badge: '🚀',
    minCompleted: 25,
    minRating: 4.95,
    unlockedFeatures: [
      'Originate sponsor-track commercial innovations & patents',
      'Negotiate co-branding contracts & royalty streams in INR',
      'Direct access to national innovation grants & angel seed pools',
    ],
    maxOrderValue: 500000,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-creator-1',
    name: 'Aarav Patel',
    role: 'MINOR_CREATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    age: 14,
    isMinor: true,
    guardianId: 'user-guardian-1',
    guardianName: 'Priya Patel',
    tier: 'Builder',
    rating: 4.9,
    completedProjectsCount: 6,
    authorizedToolTiers: [1, 2],
    location: 'Pune, Maharashtra',
    bio: '14yo robotics enthusiast & IoT tinkerer. Built solar hydroponics & crop health rovers. Passionate about sustainable agriculture sensors.',
    stemInterests: ['Robotics', 'ESP32 & IoT', 'Sensors', '3D Printing'],
    experienceHours: 128,
    nepCreditsEarned: 14,
  },
  {
    id: 'user-creator-2',
    name: 'Rohan Deshmukh',
    role: 'COLLEGE_CREATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    age: 20,
    isMinor: false,
    tier: 'Studio Lead',
    rating: 4.95,
    completedProjectsCount: 18,
    authorizedToolTiers: [1, 2, 3, 4],
    location: 'Bengaluru, Karnataka',
    bio: '3rd year B.Tech Mechatronics student at RVCE. Mentoring 12+ school students in robotics, drone flight controllers, and PCB design.',
    stemInterests: ['Embedded Systems', 'ROS2 Robotics', 'PCB Milling', 'Drone Avionics'],
    experienceHours: 420,
    nepCreditsEarned: 36,
  },
  {
    id: 'user-creator-3',
    name: 'Trisha Sen',
    role: 'MINOR_CREATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    age: 16,
    isMinor: true,
    guardianName: 'Amit Sen',
    tier: 'Idea Groomer',
    rating: 4.88,
    completedProjectsCount: 9,
    authorizedToolTiers: [1, 2],
    location: 'Kolkata, West Bengal',
    bio: 'Class 11 STEM student working on assistive devices for visually impaired peers using ultrasonic haptic arrays and edge AI vision.',
    stemInterests: ['Assistive Tech', 'Computer Vision', 'MicroPython', 'Arduino'],
    experienceHours: 195,
    nepCreditsEarned: 22,
  },
  {
    id: 'user-req-1',
    name: 'Ananya Sharma',
    role: 'STUDENT_REQUESTER',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    age: 15,
    isMinor: true,
    guardianName: 'Sunil Sharma',
    location: 'New Delhi, Delhi',
    bio: 'Grade 9 science fair participant eager to learn hands-on renewable energy prototypes and partner with peer builders.',
    stemInterests: ['Solar Energy', 'Hydroponics', 'Bio-Plastics'],
    experienceHours: 45,
    nepCreditsEarned: 6,
  },
  {
    id: 'user-mentor-1',
    name: 'Dr. Vikram Seth',
    role: 'MENTOR_VALIDATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    age: 48,
    isMinor: false,
    location: 'Hyderabad, Telangana',
    bio: 'Senior STEM Professor & ATAL Tinkering Lab (ATL) Mentor. Validating student prototypes, ensuring safety compliance, and guiding research.',
    stemInterests: ['ATL Safety Standards', 'Applied Physics', 'Circuit Theory', 'Academic Mentorship'],
    experienceHours: 850,
  },
  {
    id: 'user-guardian-1',
    name: 'Priya Patel',
    role: 'GUARDIAN',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    age: 42,
    isMinor: false,
    location: 'Pune, Maharashtra',
    bio: 'Parent & guardian of Aarav Patel. Supporting experiential learning, DPDP safety oversight, and laboratory tool permissions.',
  },
  {
    id: 'user-sponsor-1',
    name: 'Nexus Non-Profit Foundation',
    role: 'SPONSOR',
    avatarUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150',
    age: 35,
    isMinor: false,
    location: 'Pan-India',
    bio: '100% Non-profit CSR foundation providing zero-fee component grants, 3D printing supplies, and microcontroller kits to young innovators.',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-2026-001',
    title: 'Solar-Powered Automated Hydroponic Monitoring System',
    category: 'SCHOOL_SCIENCE',
    academicLevel: 'Grade 9 Science Fair',
    subjectDomain: 'Environmental Science & Electronics',
    description:
      'A compact working hydroponic plant growth chamber equipped with solar panel charging, soil moisture sensor, automated water pump, and OLED status display.',
    state: 'INTERNAL_REVIEW',
    requesterId: 'user-req-1',
    requesterName: 'Ananya Sharma',
    creatorId: 'user-creator-1',
    creatorName: 'Aarav Patel (14yo)',
    creatorAge: 14,
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Vikram Seth',
    guardianId: 'user-guardian-1',
    requiredDeliverables: [
      'Working Solar Hydroponic Model',
      'A3 Science Fair Poster',
      'Comprehensive Project Report (PDF)',
      'Explainer Pack with Viva Q&A',
    ],
    budgetCeiling: 8500,
    pricing: {
      partsCost: 3800,
      laborEstimate: 2800,
      platformServiceChargePercent: 10,
      platformServiceFee: 660,
      deliveryCost: 450,
      totalPrice: 7710,
    },
    validationPassed: false,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-22T08:30:00Z',
    buildLogs: [
      {
        id: 'log-1',
        orderId: 'ORD-2026-001',
        timestamp: '2026-08-18T14:20:00Z',
        creatorId: 'user-creator-1',
        creatorName: 'Aarav Patel',
        stage: 'Wiring & Circuit Test',
        mediaUrl: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600',
        mediaType: 'image',
        note: 'Wired the Arduino Nano with the soil moisture relay and OLED display. Solar charge controller is regulating 5V output smoothly!',
        stemConceptTag: 'Pulse Width Modulation & Closed-Loop Control',
      },
      {
        id: 'log-2',
        orderId: 'ORD-2026-001',
        timestamp: '2026-08-20T11:15:00Z',
        creatorId: 'user-creator-1',
        creatorName: 'Aarav Patel',
        stage: 'Acrylic Housing & Pump Integration',
        mediaUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600',
        mediaType: 'image',
        note: 'Laser-cut non-toxic acrylic reservoir frame. Submersible 5V water pump tested with automated moisture threshold trigger.',
        stemConceptTag: 'Capillary Action & Fluid Mechanics',
      },
    ],
    explainerPack: {
      id: 'exp-1',
      orderId: 'ORD-2026-001',
      howItWorks:
        'The hydroponic chamber uses a capacitive soil sensor to continuously measure moisture levels. When moisture drops below 30%, the microcontroller activates a 5V mini water pump powered by a lithium cell charged via a 10W solar panel. Real-time statistics are shown on an OLED screen.',
      materialsUsed: [
        'Arduino Nano Microcontroller',
        'Capacitive Soil Moisture Sensor v1.2',
        '10W Monocrystalline Solar Panel',
        'TP4056 Solar Charge Controller with 18650 Battery',
        'Submersible 5V Mini Water Pump & Silicone Tubing',
        'Laser-Cut Acrylic Reservoir',
      ],
      conceptsCovered: [
        'Photovoltaic Energy Conversion',
        'Closed-Loop Feedback Control Systems',
        'Capacitive Sensing Technology',
        'Sustainable Nutrient Delivery in Agriculture',
      ],
      vivaQuestions: [
        {
          question: 'Why is a capacitive sensor preferred over a resistive soil moisture sensor?',
          answer:
            'Capacitive sensors do not have exposed metal electrodes submerged directly in water, preventing electrode corrosion and electrolysis over prolonged usage.',
          difficulty: 'Easy',
        },
        {
          question: 'What is the role of the TP4056 module in the solar circuit?',
          answer:
            'The TP4056 acts as a constant-current/constant-voltage lithium battery charger, preventing overcharging and deep discharge of the rechargeable battery.',
          difficulty: 'Medium',
        },
        {
          question: 'How would you scale this prototype for industrial vertical farming in India?',
          answer:
            'By replacing the Arduino Nano with an IoT microcontroller (ESP32) for wireless telemetry to smartphone apps, using industrial peristaltic pumps, and incorporating EC (Electrical Conductivity) & pH monitoring sensors.',
          difficulty: 'Advanced',
        },
      ],
      audioLanguage: 'English / Hindi',
      mediaGallery: [
        {
          url: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600',
          caption: 'Microcontroller & Sensor Circuit Wiring',
          stage: 'Breadboard Prototyping',
          type: 'image',
        },
        {
          url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600',
          caption: 'Final Hydroponic Frame with Water Circulation',
          stage: 'Assembly Completed',
          type: 'image',
        },
      ],
    },
    eventsHistory: [
      {
        id: 'e-1',
        orderId: 'ORD-2026-001',
        fromState: 'DRAFT',
        toState: 'SUBMITTED',
        timestamp: '2026-08-15T10:00:00Z',
        actorId: 'user-req-1',
        actorName: 'Ananya Sharma',
        actorRole: 'STUDENT_REQUESTER',
      },
      {
        id: 'e-2',
        orderId: 'ORD-2026-001',
        fromState: 'SUBMITTED',
        toState: 'SCOPED',
        timestamp: '2026-08-15T12:00:00Z',
        actorId: 'user-mentor-1',
        actorName: 'Dr. Vikram Seth',
        actorRole: 'MENTOR_VALIDATOR',
        comment: 'Scoped into 3 days build timeline with Arduino & solar charge circuit.',
      },
      {
        id: 'e-3',
        orderId: 'ORD-2026-001',
        fromState: 'SCOPED',
        toState: 'PRICED',
        timestamp: '2026-08-15T12:30:00Z',
        actorId: 'user-mentor-1',
        actorName: 'Dr. Vikram Seth',
        actorRole: 'MENTOR_VALIDATOR',
      },
      {
        id: 'e-4',
        orderId: 'ORD-2026-001',
        fromState: 'PRICED',
        toState: 'ACCEPTED_BY_REQUESTER',
        timestamp: '2026-08-15T14:00:00Z',
        actorId: 'user-req-1',
        actorName: 'Ananya Sharma',
        actorRole: 'STUDENT_REQUESTER',
      },
      {
        id: 'e-5',
        orderId: 'ORD-2026-001',
        fromState: 'ACCEPTED_BY_REQUESTER',
        toState: 'CREATOR_MATCHED',
        timestamp: '2026-08-15T15:00:00Z',
        actorId: 'user-creator-1',
        actorName: 'Aarav Patel',
        actorRole: 'MINOR_CREATOR',
        comment: 'Matched to Aarav Patel (Verified Builder, Guardian approved for Class 1 & 2 tools).',
      },
      {
        id: 'e-6',
        orderId: 'ORD-2026-001',
        fromState: 'CREATOR_MATCHED',
        toState: 'IN_PROGRESS',
        timestamp: '2026-08-16T09:00:00Z',
        actorId: 'user-creator-1',
        actorName: 'Aarav Patel',
        actorRole: 'MINOR_CREATOR',
      },
      {
        id: 'e-7',
        orderId: 'ORD-2026-001',
        fromState: 'IN_PROGRESS',
        toState: 'INTERNAL_REVIEW',
        timestamp: '2026-08-22T08:30:00Z',
        actorId: 'user-creator-1',
        actorName: 'Aarav Patel',
        actorRole: 'MINOR_CREATOR',
        comment: 'Submitted for Mentor Validation Gate.',
      },
    ],
  },
  {
    id: 'ORD-2026-002',
    title: 'AI-Powered Gesture Controlled Robotic Prosthetic Hand',
    category: 'COLLEGE_ENGINEERING',
    academicLevel: 'B.Tech Robotics Capstone',
    subjectDomain: 'Biomechatronics & Embedded AI',
    description:
      'A 5-degree-of-freedom prosthetic hand powered by servo motors, controlled via surface EMG muscle sensors and onboard lightweight neural network gesture classification.',
    state: 'IN_PROGRESS',
    requesterId: 'user-req-2',
    requesterName: 'Dr. Elena Vance',
    creatorId: 'user-creator-2',
    creatorName: 'Rohan Deshmukh (Studio Lead)',
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Vikram Seth',
    requiredDeliverables: [
      '3D-Printed Prosthetic Rig',
      'Custom PCB & EMG Sensor Array',
      'ROS2 Telemetry Node Source Code',
      'Explainer Pack & Video Demo',
    ],
    budgetCeiling: 28000,
    pricing: {
      partsCost: 14000,
      laborEstimate: 8500,
      platformServiceChargePercent: 12,
      platformServiceFee: 2700,
      deliveryCost: 800,
      totalPrice: 26000,
    },
    validationPassed: false,
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-21T16:45:00Z',
    buildLogs: [
      {
        id: 'log-201',
        orderId: 'ORD-2026-002',
        timestamp: '2026-08-14T10:00:00Z',
        creatorId: 'user-creator-2',
        creatorName: 'Rohan Deshmukh',
        stage: '3D Printing TPU Fingers',
        mediaUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600',
        mediaType: 'image',
        note: 'Printed flexible TPU joint ligaments for smooth tendon-driven articulation.',
      },
    ],
    eventsHistory: [
      {
        id: 'e-201',
        orderId: 'ORD-2026-002',
        fromState: 'DRAFT',
        toState: 'SUBMITTED',
        timestamp: '2026-08-10T09:00:00Z',
        actorId: 'user-req-2',
        actorName: 'Dr. Elena Vance',
        actorRole: 'RESEARCHER_REQUESTER',
      },
    ],
  },
];

export const INITIAL_IDEAS: Idea[] = [
  {
    id: 'IDEA-101',
    title: 'Ocean-Plastic River Bubble Barrier & Automated Collector',
    problemStatement:
      'Indian rivers transport macro-plastic waste into ocean ecosystems every year, causing severe harm to marine biology.',
    proposedSolution:
      'A floating perforated tube powered by river currents that emits a curtain of air bubbles, redirecting floating plastics to an automated solar conveyor scoop without obstructing river traffic or fish migration.',
    category: 'SCHOOL_SCIENCE',
    tags: ['Clean River Tech', 'Renewable Energy', 'Automation', 'Make in India STEM'],
    originatorId: 'user-creator-1',
    originatorName: 'Aarav Patel',
    originatorAge: 14,
    status: 'READY_FOR_PROTOTYPE',
    currentRevisionNumber: 2,
    revisions: [
      {
        revisionNumber: 1,
        timestamp: '2026-08-01T12:00:00Z',
        authorId: 'user-creator-1',
        authorName: 'Aarav Patel',
        authorRole: 'MINOR_CREATOR',
        changesSummary: 'Initial idea concept submission',
        updatedScope: 'Small scale river bubble barrier using aquarium air pump.',
        updatedBOM: ['Aquarium Air Pump', 'Perforated PVC Tube', 'Mesh Net Collector'],
        estimatedBuildHours: 12,
      },
      {
        revisionNumber: 2,
        timestamp: '2026-08-08T15:30:00Z',
        authorId: 'user-mentor-1',
        authorName: 'Dr. Vikram Seth (Mentor)',
        authorRole: 'MENTOR_VALIDATOR',
        changesSummary: 'Groomed scope: Added solar micro-conveyor & hydro-turbine pump concept.',
        updatedScope: 'Autonomous scale model with solar conveyor belt and air curtain diffuser.',
        updatedBOM: [
          '12V Solar Panel & Battery',
          'Miniature Air Blower',
          'Perforated Silicone Hose',
          'DC Conveyor Belt Motor',
          'Custom 3D Printed Trash Collector Hopper',
        ],
        estimatedBuildHours: 24,
      },
    ],
    contributorLedger: [
      {
        userId: 'user-creator-1',
        userName: 'Aarav Patel',
        roleInIdea: 'Originator',
        contributionPercentage: 60,
      },
      {
        userId: 'user-mentor-1',
        userName: 'Dr. Vikram Seth',
        roleInIdea: 'Groomer',
        contributionPercentage: 20,
      },
      {
        userId: 'user-creator-2',
        userName: 'Rohan Deshmukh',
        roleInIdea: 'Builder',
        contributionPercentage: 20,
      },
    ],
    feasibilityScore: 92,
    estimatedFundingNeeded: 25000,
    createdAt: '2026-08-01T12:00:00Z',
  },
];

export const INITIAL_ESCROW: EscrowTransaction[] = [
  {
    id: 'ESCROW-901',
    ideaId: 'IDEA-101',
    sponsorId: 'user-sponsor-1',
    sponsorName: 'Nexus Innovation Labs India',
    totalAmount: 25000,
    escrowStatus: 'HELD',
    milestones: [
      {
        title: 'Milestone 1: BOM Sourcing & Air Curtain Fluid Dynamics Test',
        amount: 8000,
        isReleased: true,
      },
      {
        title: 'Milestone 2: Solar Conveyor Integration & Flume Tank Trial',
        amount: 11000,
        isReleased: false,
      },
      {
        title: 'Milestone 3: Final Validation Gate & Explainer Pack Delivery',
        amount: 6000,
        isReleased: false,
      },
    ],
  },
];

export const INITIAL_AGREEMENTS: SponsorshipAgreement[] = [
  {
    id: 'AGR-301',
    ideaId: 'IDEA-101',
    sponsorId: 'user-sponsor-1',
    sponsorName: 'Nexus Innovation Labs India',
    originatorName: 'Aarav Patel (Guardian Co-Signed)',
    fundingAmount: 25000,
    revenueSharePercent: 15,
    coBrandingRights: 'Nexus Young Innovator Grantee badge on model and explainer media',
    ipTerms: 'Originator retains 70% IP equity; Sponsor holds exclusive 3-year commercialization right in India.',
    guardianSigned: true,
    signedAt: '2026-08-12T14:00:00Z',
  },
];

export const INITIAL_MODERATED_MESSAGES: ModeratedMessage[] = [
  {
    id: 'msg-1',
    orderId: 'ORD-2026-001',
    senderId: 'user-req-1',
    senderName: 'Ananya Sharma',
    senderRole: 'STUDENT_REQUESTER',
    receiverId: 'user-creator-1',
    receiverName: 'Aarav Patel (Minor Creator)',
    messageText: 'Hi Aarav! Could you please make sure the LED display is bright blue?',
    timestamp: '2026-08-17T16:00:00Z',
    flaggedKeywords: [],
    isApproved: true,
  },
  {
    id: 'msg-2',
    orderId: 'ORD-2026-001',
    senderId: 'user-creator-1',
    senderName: 'Aarav Patel',
    senderRole: 'MINOR_CREATOR',
    receiverId: 'user-req-1',
    receiverName: 'Ananya Sharma',
    messageText: 'Yes! I have attached a 0.96 inch I2C OLED display with crisp blue text on black background.',
    timestamp: '2026-08-17T16:05:00Z',
    flaggedKeywords: [],
    isApproved: true,
  },
];

export const INITIAL_STORIES: InnovationStory[] = [
  {
    id: 'STORY-001',
    title: 'How a 14-Year-Old Built an AI Autonomous Farm Rover in Pune',
    subtitle: 'From a broken toy car chassis to a solar-assisted crop health rover: The story of Aarav & Rohan’s cross-grade maker collaboration.',
    author: 'Aarav Patel & Rohan Deshmukh',
    authorAge: 14,
    authorRole: 'Student Builder & College Mentor',
    authorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    category: 'ROBOTICS',
    readTime: '4 min read',
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800',
    tags: ['ESP32', 'Edge AI', 'Solar Power', 'NEP 2020 Experiential Credit'],
    summary: 'Using 100% non-profit open grants, 14-year-old Aarav partnered with mechatronics undergraduate Rohan to engineer a 4WD soil analysis robot with offline computer vision.',
    fullContent: `
### The Spark
During a weekend visit to his grandparents' farm near Pune, Aarav noticed how fungal leaf rust often destroys tomato crops before farmers spot the early signs. Instead of a theoretical science fair poster, Aarav wanted to build a working robotic scout that could drive autonomously between crop furrows.

### Connecting Through Young Dream Innovators
Aarav posted an initial sketch on the Young Innovator Idea Board. Rohan Deshmukh (20yo, Mechatronics student at RVCE Bengaluru) saw the post and volunteered as an engineering mentor.

Together, they scoped the bill of materials:
- **Chassis:** Laser-cut acrylic & 3D printed PETG suspension (Class 2 tools authorized by Aarav's guardian).
- **Core Controller:** ESP32-CAM with TinyML quantized neural network for on-device leaf spot detection.
- **Power System:** 10W monocrystalline solar cell with MPPT charging circuit.

### Zero-Profit Grant Funding
Through the community non-profit grant pool funded by CSR sponsors, 100% of the raw components (₹3,850) were delivered directly to Aarav's home lab without any platform markups or fees.

### What Aarav Learned
"I used to think AI was only for big software companies. With Rohan's mentorship, I flashed micro-Python onto an ESP32 and trained a custom TensorFlow Lite model with 80 leaf photos! Building something real taught me more than an entire textbook chapter."
    `,
    keyConcepts: [
      'Convolutional Neural Networks (TinyML on Edge)',
      'Solar Photovoltaic MPPT Efficiency',
      'I2C Sensor Multiplexing & MicroPython',
      'Mechanical Gear Ratio Torque Calculation',
    ],
    prototypeSpecs: [
      { label: 'Drive System', value: '4x Metal Gear TT Motors (1:48 ratio)' },
      { label: 'Compute', value: 'ESP32-S3 Dual Core 240MHz + OV2640 Camera' },
      { label: 'Battery Life', value: '6.5 hours continuous patrol (Solar-Assisted)' },
      { label: 'Inference Latency', value: '180ms per frame offline' },
    ],
    materialsCostINR: 3850,
    grantFundedBy: 'Pan-India Youth STEM Non-Profit Fund',
    publishedAt: '2 days ago',
    likesCount: 142,
    verifiedByMentor: 'Dr. Vikram Seth (ATL Mentor)',
  },
  {
    id: 'STORY-002',
    title: 'Haptic Vision: Class 11 Student Designs Ultrasonic Smart Glasses',
    subtitle: 'Trisha Sen engineered open-source multi-directional spatial audio glasses to empower visually impaired students in navigation.',
    author: 'Trisha Sen',
    authorAge: 16,
    authorRole: 'Idea Groomer & High-School Maker',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    category: 'COMMUNITY_IMPACT',
    readTime: '5 min read',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
    tags: ['Assistive Tech', 'Arduino Pro Mini', 'Haptics', 'Open Source'],
    summary: 'A lightweight 3D-printed wearable that converts obstacle proximity into gentle haptic pulses, enabling independent indoor navigation.',
    fullContent: `
### Real-World Inspiration
Trisha noticed that visually impaired classmates frequently bumped into low-hanging tree branches and elevated stair railings that traditional white canes miss.

### Collaborative Development
Working in an open innovation pod with two peer makers, Trisha designed custom 3D printed temple frames housing dual ultrasonic transducers angled at 45 degrees upward and forward.

### Results & Open Source Release
The entire CAD files and firmware have been published free for public ATAL Tinkering Labs (ATLs) across India, costing less than ₹1,200 in raw parts.
    `,
    keyConcepts: [
      'Ultrasonic Time-of-Flight Wave Reflection',
      'PWM Haptic Motor Modulation',
      'Ergonomic Biocompatible 3D Printing (PLA+)',
      'Low-Power Sleep Modes (8mA active)',
    ],
    prototypeSpecs: [
      { label: 'Detection Range', value: '2cm to 400cm with ±3mm accuracy' },
      { label: 'Weight', value: '48 grams (featherlight)' },
      { label: 'Battery', value: 'LiPo 500mAh with USB-C safety charging' },
      { label: 'Cost to Assemble', value: '₹1,180 (100% Grant Covered)' },
    ],
    materialsCostINR: 1180,
    grantFundedBy: 'National Inclusive STEM Foundation',
    publishedAt: '5 days ago',
    likesCount: 219,
    verifiedByMentor: 'Prof. Anjali Roy (IIT Kharagpur Alum)',
  },
  {
    id: 'STORY-003',
    title: 'Clean Water Everywhere: The Low-Cost Solar Thermal Condenser',
    subtitle: 'Grade 9 student Ananya Sharma collaborated with college mentors to distill greywater using parabolic mirrors and heat pipes.',
    author: 'Ananya Sharma',
    authorAge: 15,
    authorRole: 'Student Requester & Explorer',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    category: 'CLEANTECH',
    readTime: '3 min read',
    coverImage: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800',
    tags: ['Thermodynamics', 'Clean Water', 'Solar Thermal', 'Science Fair'],
    summary: 'A zero-electricity distillation unit that purifies brackish water using optical solar concentrators and copper heat dissipation.',
    fullContent: `
### The Challenge
Access to clean distilled water for rural science labs is often limited by electricity access. Ananya wanted to create a passive, solar-driven distillation system that can be fabricated using readily available scrap materials.

### Pod Collaboration
Ananya teamed up with university mentors who helped verify the thermodynamics equations and safe pressure relief valves.
    `,
    keyConcepts: [
      'Latent Heat of Vaporization',
      'Parabolic Reflector Geometry',
      'Total Dissolved Solids (TDS) Measurement',
      'Convective Heat Transfer',
    ],
    prototypeSpecs: [
      { label: 'Daily Yield', value: '3.2 Litres pure water / 6 hours sunlight' },
      { label: 'TDS Reduction', value: 'From 850 PPM down to 14 PPM' },
      { label: 'Materials Used', value: 'Recycled Aluminum, Copper Pipe, Glass Vessel' },
      { label: 'Operating Cost', value: '₹0 (Zero Electricity)' },
    ],
    materialsCostINR: 2100,
    grantFundedBy: 'Green Earth Young Innovators Fellowship',
    publishedAt: '1 week ago',
    likesCount: 98,
    verifiedByMentor: 'Dr. Vikram Seth (ATL Mentor)',
  },
];

export const INITIAL_PODS: InnovationPod[] = [
  {
    id: 'POD-101',
    title: 'Autonomous Agro-Bot Collective',
    domain: 'Agricultural Robotics & Edge Vision',
    leadStudent: 'Aarav Patel (14yo)',
    leadStudentAge: 14,
    mentorName: 'Rohan Deshmukh (Mechatronics Senior)',
    schoolOrCollege: 'Vibgyor High, Pune & RVCE Bengaluru',
    teamSize: 3,
    maxTeamSize: 4,
    lookingFor: ['Flutter App Designer', 'Sensor Calibration Tester'],
    description: 'Building small-footprint solar rovers to detect soil nitrogen levels and early leaf blight for organic farms.',
    progressPercent: 75,
    grantApprovedINR: 8500,
    badges: ['Active Sprint', 'ATL Lab Verified', 'Open Hardware'],
  },
  {
    id: 'POD-102',
    title: 'Assistive Tech Haptic Pod',
    domain: 'Accessible Wearables & Ultrasonic Spatial Sound',
    leadStudent: 'Trisha Sen (16yo)',
    leadStudentAge: 16,
    mentorName: 'Prof. Anjali Roy',
    schoolOrCollege: 'DPS Ruby Park, Kolkata',
    teamSize: 2,
    maxTeamSize: 3,
    lookingFor: ['3D CAD Designer (Fusion 360)', 'MicroPython Dev'],
    description: 'Creating affordable obstacle detection wearables for visually impaired school children across government schools.',
    progressPercent: 60,
    grantApprovedINR: 5200,
    badges: ['Social Good', 'Open Source', 'Field Testing'],
  },
  {
    id: 'POD-103',
    title: 'Clean Energy & Solar Stills',
    domain: 'Thermal Energy & Environmental Sensing',
    leadStudent: 'Ananya Sharma (15yo)',
    leadStudentAge: 15,
    mentorName: 'Dr. Vikram Seth',
    schoolOrCollege: 'Modern School, New Delhi',
    teamSize: 2,
    maxTeamSize: 4,
    lookingFor: ['Data Logger Dev (ESP32)', 'Poster Designer'],
    description: 'Developing passive solar water purifiers and automated TDS telemetry for rural schools.',
    progressPercent: 40,
    grantApprovedINR: 4000,
    badges: ['NEP 2020 Aligned', 'Science Fair Prep'],
  },
];
