import {
  User,
  Order,
  Idea,
  EscrowTransaction,
  SponsorshipAgreement,
  ModeratedMessage,
  CreatorTierInfo,
} from '../types';

export const CREATOR_TIERS: CreatorTierInfo[] = [
  {
    level: 'Apprentice',
    title: 'Apprentice Maker',
    badge: '🌱',
    minCompleted: 0,
    minRating: 0.0,
    unlockedFeatures: [
      'Simple pre-scoped STEM science kits',
      'Mentor-guided build queues',
      'Class 1 safe tools (scissors, glue, breadboard, 5V Arduino)',
    ],
    maxOrderValue: 5000,
  },
  {
    level: 'Builder',
    title: 'Certified Student Builder',
    badge: '⚡',
    minCompleted: 3,
    minRating: 4.5,
    unlockedFeatures: [
      'Custom school science fair & robotics project builds',
      'BOM optimization & schematic design proposals',
      'Class 2 tools (low-voltage soldering, 3D printers with guardian consent)',
    ],
    maxOrderValue: 15000,
  },
  {
    level: 'Idea Groomer',
    title: 'Community Idea Groomer',
    badge: '💡',
    minCompleted: 8,
    minRating: 4.8,
    unlockedFeatures: [
      'Lead RFC grooming discussions with young inventors',
      'Mentor Apprentice creators across India',
      'Earn contributor ledger equity splits on groomed ideas',
    ],
    maxOrderValue: 35000,
  },
  {
    level: 'Studio Lead',
    title: 'Maker Studio Lead',
    badge: '🛠️',
    minCompleted: 15,
    minRating: 4.9,
    unlockedFeatures: [
      'Form student squads for complex engineering & research orders',
      'Direct college lab & researcher project assignments',
      'Revenue share on squad build outputs & prototyping grants',
    ],
    maxOrderValue: 100000,
  },
  {
    level: 'Young Entrepreneur',
    title: 'Young Entrepreneur Inventor',
    badge: '🚀',
    minCompleted: 25,
    minRating: 4.95,
    unlockedFeatures: [
      'Originate sponsor-track commercial innovations & patents',
      'Negotiate co-branding contracts & royalty streams in INR',
      'Direct access to national innovation grants & angel seed pools',
    ],
    maxOrderValue: 500000,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-req-1',
    name: 'Ananya Sharma',
    role: 'STUDENT_REQUESTER',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    age: 15,
    isMinor: true,
    guardianName: 'Sunil Sharma',
  },
  {
    id: 'user-req-2',
    name: 'Dr. Elena Vance',
    role: 'RESEARCHER_REQUESTER',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    age: 34,
    isMinor: false,
  },
  {
    id: 'user-creator-1',
    name: 'Aarav Patel',
    role: 'MINOR_CREATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    age: 14,
    isMinor: true,
    guardianId: 'user-guardian-1',
    guardianName: 'Priya Patel',
    tier: 'Builder',
    rating: 4.9,
    completedProjectsCount: 6,
    authorizedToolTiers: [1, 2],
  },
  {
    id: 'user-creator-2',
    name: 'Rohan Deshmukh',
    role: 'COLLEGE_CREATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    age: 20,
    isMinor: false,
    tier: 'Studio Lead',
    rating: 4.95,
    completedProjectsCount: 18,
    authorizedToolTiers: [1, 2, 3, 4],
  },
  {
    id: 'user-guardian-1',
    name: 'Priya Patel',
    role: 'GUARDIAN',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    age: 42,
    isMinor: false,
  },
  {
    id: 'user-mentor-1',
    name: 'Dr. Vikram Seth',
    role: 'MENTOR_VALIDATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    age: 48,
    isMinor: false,
  },
  {
    id: 'user-sponsor-1',
    name: 'Nexus Innovation Labs',
    role: 'SPONSOR',
    avatarUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150',
    age: 35,
    isMinor: false,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-2026-001',
    title: 'Solar-Powered Automated Hydroponic Monitoring System',
    category: 'SCHOOL_SCIENCE',
    academicLevel: 'Grade 9 Science Fair',
    subjectDomain: 'Environmental Science & Electronics',
    description:
      'A compact working hydroponic plant growth chamber equipped with solar panel charging, soil moisture sensor, automated water pump, and OLED status display.',
    state: 'INTERNAL_REVIEW',
    requesterId: 'user-req-1',
    requesterName: 'Ananya Sharma',
    creatorId: 'user-creator-1',
    creatorName: 'Aarav Patel (14yo)',
    creatorAge: 14,
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Vikram Seth',
    guardianId: 'user-guardian-1',
    requiredDeliverables: [
      'Working Solar Hydroponic Model',
      'A3 Science Fair Poster',
      'Comprehensive Project Report (PDF)',
      'Explainer Pack with Viva Q&A',
    ],
    budgetCeiling: 8500,
    pricing: {
      partsCost: 3800,
      laborEstimate: 2800,
      platformServiceChargePercent: 10,
      platformServiceFee: 660,
      deliveryCost: 450,
      totalPrice: 7710,
    },
    validationPassed: false,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-22T08:30:00Z',
    buildLogs: [
      {
        id: 'log-1',
        orderId: 'ORD-2026-001',
        timestamp: '2026-08-18T14:20:00Z',
        creatorId: 'user-creator-1',
        creatorName: 'Aarav Patel',
        stage: 'Wiring & Circuit Test',
        mediaUrl: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600',
        mediaType: 'image',
        note: 'Wired the Arduino Nano with the soil moisture relay and OLED display. Solar charge controller is regulating 5V output smoothly!',
        stemConceptTag: 'Pulse Width Modulation & Closed-Loop Control',
      },
      {
        id: 'log-2',
        orderId: 'ORD-2026-001',
        timestamp: '2026-08-20T11:15:00Z',
        creatorId: 'user-creator-1',
        creatorName: 'Aarav Patel',
        stage: 'Acrylic Housing & Pump Integration',
        mediaUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600',
        mediaType: 'image',
        note: 'Laser-cut non-toxic acrylic reservoir frame. Submersible 5V water pump tested with automated moisture threshold trigger.',
        stemConceptTag: 'Capillary Action & Fluid Mechanics',
      },
    ],
    explainerPack: {
      id: 'exp-1',
      orderId: 'ORD-2026-001',
      howItWorks:
        'The hydroponic chamber uses a capacitive soil sensor to continuously measure moisture levels. When moisture drops below 30%, the microcontroller activates a 5V mini water pump powered by a lithium cell charged via a 10W solar panel. Real-time statistics are shown on an OLED screen.',
      materialsUsed: [
        'Arduino Nano Microcontroller',
        'Capacitive Soil Moisture Sensor v1.2',
        '10W Monocrystalline Solar Panel',
        'TP4056 Solar Charge Controller with 18650 Battery',
        'Submersible 5V Mini Water Pump & Silicone Tubing',
        'Laser-Cut Acrylic Reservoir',
      ],
      conceptsCovered: [
        'Photovoltaic Energy Conversion',
        'Closed-Loop Feedback Control Systems',
        'Capacitive Sensing Technology',
        'Sustainable Nutrient Delivery in Agriculture',
      ],
      vivaQuestions: [
        {
          question: 'Why is a capacitive sensor preferred over a resistive soil moisture sensor?',
          answer:
            'Capacitive sensors do not have exposed metal electrodes submerged directly in water, preventing electrode corrosion and electrolysis over prolonged usage.',
          difficulty: 'Easy',
        },
        {
          question: 'What is the role of the TP4056 module in the solar circuit?',
          answer:
            'The TP4056 acts as a constant-current/constant-voltage lithium battery charger, preventing overcharging and deep discharge of the rechargeable battery.',
          difficulty: 'Medium',
        },
        {
          question: 'How would you scale this prototype for industrial vertical farming in India?',
          answer:
            'By replacing the Arduino Nano with an IoT microcontroller (ESP32) for wireless telemetry to smartphone apps, using industrial peristaltic pumps, and incorporating EC (Electrical Conductivity) & pH monitoring sensors.',
          difficulty: 'Advanced',
        },
      ],
      audioLanguage: 'English / Hindi',
      mediaGallery: [
        {
          url: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=600',
          caption: 'Microcontroller & Sensor Circuit Wiring',
          stage: 'Breadboard Prototyping',
          type: 'image',
        },
        {
          url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600',
          caption: 'Final Hydroponic Frame with Water Circulation',
          stage: 'Assembly Completed',
          type: 'image',
        },
      ],
    },
    eventsHistory: [
      {
        id: 'e-1',
        orderId: 'ORD-2026-001',
        fromState: 'DRAFT',
        toState: 'SUBMITTED',
        timestamp: '2026-08-15T10:00:00Z',
        actorId: 'user-req-1',
        actorName: 'Ananya Sharma',
        actorRole: 'STUDENT_REQUESTER',
      },
      {
        id: 'e-2',
        orderId: 'ORD-2026-001',
        fromState: 'SUBMITTED',
        toState: 'SCOPED',
        timestamp: '2026-08-15T12:00:00Z',
        actorId: 'user-mentor-1',
        actorName: 'Dr. Vikram Seth',
        actorRole: 'MENTOR_VALIDATOR',
        comment: 'Scoped into 3 days build timeline with Arduino & solar charge circuit.',
      },
      {
        id: 'e-3',
        orderId: 'ORD-2026-001',
        fromState: 'SCOPED',
        toState: 'PRICED',
        timestamp: '2026-08-15T12:30:00Z',
        actorId: 'user-mentor-1',
        actorName: 'Dr. Vikram Seth',
        actorRole: 'MENTOR_VALIDATOR',
      },
      {
        id: 'e-4',
        orderId: 'ORD-2026-001',
        fromState: 'PRICED',
        toState: 'ACCEPTED_BY_REQUESTER',
        timestamp: '2026-08-15T14:00:00Z',
        actorId: 'user-req-1',
        actorName: 'Ananya Sharma',
        actorRole: 'STUDENT_REQUESTER',
      },
      {
        id: 'e-5',
        orderId: 'ORD-2026-001',
        fromState: 'ACCEPTED_BY_REQUESTER',
        toState: 'CREATOR_MATCHED',
        timestamp: '2026-08-15T15:00:00Z',
        actorId: 'user-creator-1',
        actorName: 'Aarav Patel',
        actorRole: 'MINOR_CREATOR',
        comment: 'Matched to Aarav Patel (Verified Builder, Guardian approved for Class 1 & 2 tools).',
      },
      {
        id: 'e-6',
        orderId: 'ORD-2026-001',
        fromState: 'CREATOR_MATCHED',
        toState: 'IN_PROGRESS',
        timestamp: '2026-08-16T09:00:00Z',
        actorId: 'user-creator-1',
        actorName: 'Aarav Patel',
        actorRole: 'MINOR_CREATOR',
      },
      {
        id: 'e-7',
        orderId: 'ORD-2026-001',
        fromState: 'IN_PROGRESS',
        toState: 'INTERNAL_REVIEW',
        timestamp: '2026-08-22T08:30:00Z',
        actorId: 'user-creator-1',
        actorName: 'Aarav Patel',
        actorRole: 'MINOR_CREATOR',
        comment: 'Submitted for Mentor Validation Gate.',
      },
    ],
  },
  {
    id: 'ORD-2026-002',
    title: 'AI-Powered Gesture Controlled Robotic Prosthetic Hand',
    category: 'COLLEGE_ENGINEERING',
    academicLevel: 'B.Tech Robotics Capstone',
    subjectDomain: 'Biomechatronics & Embedded AI',
    description:
      'A 5-degree-of-freedom prosthetic hand powered by servo motors, controlled via surface EMG muscle sensors and onboard lightweight neural network gesture classification.',
    state: 'IN_PROGRESS',
    requesterId: 'user-req-2',
    requesterName: 'Dr. Elena Vance',
    creatorId: 'user-creator-2',
    creatorName: 'Rohan Deshmukh (Studio Lead)',
    mentorId: 'user-mentor-1',
    mentorName: 'Dr. Vikram Seth',
    requiredDeliverables: [
      '3D-Printed Prosthetic Rig',
      'Custom PCB & EMG Sensor Array',
      'ROS2 Telemetry Node Source Code',
      'Explainer Pack & Video Demo',
    ],
    budgetCeiling: 28000,
    pricing: {
      partsCost: 14000,
      laborEstimate: 8500,
      platformServiceChargePercent: 12,
      platformServiceFee: 2700,
      deliveryCost: 800,
      totalPrice: 26000,
    },
    validationPassed: false,
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-21T16:45:00Z',
    buildLogs: [
      {
        id: 'log-201',
        orderId: 'ORD-2026-002',
        timestamp: '2026-08-14T10:00:00Z',
        creatorId: 'user-creator-2',
        creatorName: 'Rohan Deshmukh',
        stage: '3D Printing TPU Fingers',
        mediaUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600',
        mediaType: 'image',
        note: 'Printed flexible TPU joint ligaments for smooth tendon-driven articulation.',
      },
    ],
    eventsHistory: [
      {
        id: 'e-201',
        orderId: 'ORD-2026-002',
        fromState: 'DRAFT',
        toState: 'SUBMITTED',
        timestamp: '2026-08-10T09:00:00Z',
        actorId: 'user-req-2',
        actorName: 'Dr. Elena Vance',
        actorRole: 'RESEARCHER_REQUESTER',
      },
    ],
  },
];

export const INITIAL_IDEAS: Idea[] = [
  {
    id: 'IDEA-101',
    title: 'Ocean-Plastic River Bubble Barrier & Automated Collector',
    problemStatement:
      'Indian rivers transport macro-plastic waste into ocean ecosystems every year, causing severe harm to marine biology.',
    proposedSolution:
      'A floating perforated tube powered by river currents that emits a curtain of air bubbles, redirecting floating plastics to an automated solar conveyor scoop without obstructing river traffic or fish migration.',
    category: 'SCHOOL_SCIENCE',
    tags: ['Clean River Tech', 'Renewable Energy', 'Automation', 'Make in India STEM'],
    originatorId: 'user-creator-1',
    originatorName: 'Aarav Patel',
    originatorAge: 14,
    status: 'READY_FOR_PROTOTYPE',
    currentRevisionNumber: 2,
    revisions: [
      {
        revisionNumber: 1,
        timestamp: '2026-08-01T12:00:00Z',
        authorId: 'user-creator-1',
        authorName: 'Aarav Patel',
        authorRole: 'MINOR_CREATOR',
        changesSummary: 'Initial idea concept submission',
        updatedScope: 'Small scale river bubble barrier using aquarium air pump.',
        updatedBOM: ['Aquarium Air Pump', 'Perforated PVC Tube', 'Mesh Net Collector'],
        estimatedBuildHours: 12,
      },
      {
        revisionNumber: 2,
        timestamp: '2026-08-08T15:30:00Z',
        authorId: 'user-mentor-1',
        authorName: 'Dr. Vikram Seth (Mentor)',
        authorRole: 'MENTOR_VALIDATOR',
        changesSummary: 'Groomed scope: Added solar micro-conveyor & hydro-turbine pump concept.',
        updatedScope: 'Autonomous scale model with solar conveyor belt and air curtain diffuser.',
        updatedBOM: [
          '12V Solar Panel & Battery',
          'Miniature Air Blower',
          'Perforated Silicone Hose',
          'DC Conveyor Belt Motor',
          'Custom 3D Printed Trash Collector Hopper',
        ],
        estimatedBuildHours: 24,
      },
    ],
    contributorLedger: [
      {
        userId: 'user-creator-1',
        userName: 'Aarav Patel',
        roleInIdea: 'Originator',
        contributionPercentage: 60,
      },
      {
        userId: 'user-mentor-1',
        userName: 'Dr. Vikram Seth',
        roleInIdea: 'Groomer',
        contributionPercentage: 20,
      },
      {
        userId: 'user-creator-2',
        userName: 'Rohan Deshmukh',
        roleInIdea: 'Builder',
        contributionPercentage: 20,
      },
    ],
    feasibilityScore: 92,
    estimatedFundingNeeded: 25000,
    createdAt: '2026-08-01T12:00:00Z',
  },
];

export const INITIAL_ESCROW: EscrowTransaction[] = [
  {
    id: 'ESCROW-901',
    ideaId: 'IDEA-101',
    sponsorId: 'user-sponsor-1',
    sponsorName: 'Nexus Innovation Labs India',
    totalAmount: 25000,
    escrowStatus: 'HELD',
    milestones: [
      {
        title: 'Milestone 1: BOM Sourcing & Air Curtain Fluid Dynamics Test',
        amount: 8000,
        isReleased: true,
      },
      {
        title: 'Milestone 2: Solar Conveyor Integration & Flume Tank Trial',
        amount: 11000,
        isReleased: false,
      },
      {
        title: 'Milestone 3: Final Validation Gate & Explainer Pack Delivery',
        amount: 6000,
        isReleased: false,
      },
    ],
  },
];

export const INITIAL_AGREEMENTS: SponsorshipAgreement[] = [
  {
    id: 'AGR-301',
    ideaId: 'IDEA-101',
    sponsorId: 'user-sponsor-1',
    sponsorName: 'Nexus Innovation Labs India',
    originatorName: 'Aarav Patel (Guardian Co-Signed)',
    fundingAmount: 25000,
    revenueSharePercent: 15,
    coBrandingRights: 'Nexus Young Innovator Grantee badge on model and explainer media',
    ipTerms: 'Originator retains 70% IP equity; Sponsor holds exclusive 3-year commercialization right in India.',
    guardianSigned: true,
    signedAt: '2026-08-12T14:00:00Z',
  },
];

export const INITIAL_MODERATED_MESSAGES: ModeratedMessage[] = [
  {
    id: 'msg-1',
    orderId: 'ORD-2026-001',
    senderId: 'user-req-1',
    senderName: 'Ananya Sharma',
    senderRole: 'STUDENT_REQUESTER',
    receiverId: 'user-creator-1',
    receiverName: 'Aarav Patel (Minor Creator)',
    messageText: 'Hi Aarav! Could you please make sure the LED display is bright blue?',
    timestamp: '2026-08-17T16:00:00Z',
    flaggedKeywords: [],
    isApproved: true,
  },
  {
    id: 'msg-2',
    orderId: 'ORD-2026-001',
    senderId: 'user-creator-1',
    senderName: 'Aarav Patel',
    senderRole: 'MINOR_CREATOR',
    receiverId: 'user-req-1',
    receiverName: 'Ananya Sharma',
    messageText: 'Yes! I have attached a 0.96 inch I2C OLED display with crisp blue text on black background.',
    timestamp: '2026-08-17T16:05:00Z',
    flaggedKeywords: [],
    isApproved: true,
  },
];
